#!/usr/bin/env bash
# Install nginx and start it
sudo apt-get -y install nginx

# Firewall setting: Allow Nginx to serve on HTTP
sudo ufw allow 'Nginx HTTP'

# Override the default index file served as home page
sudo echo "Holberton School" >> /var/www/html/index.html

#Give the user  ownership to website files
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www

# Redirect to /redirect_me to a youtube video
sudo sed -i '37i\rewrite ^/redirect_me https://www.https://www.linkedin.com/in/solomon-gebreegziabher-17b5251b2/ permanent;' /etc/nginx/sites-available/default

sudo service nginx start
